apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "openshift-kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "openshift-kube-state-metrics.labels.chart" . | indent 4 }}
  name: {{ template "openshift-kube-state-metrics.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "openshift-kube-state-metrics.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "openshift-kube-state-metrics.name" . }}
  namespace: {{ .Release.Namespace }}