apiVersion: apps/v1beta1
# Kubernetes versions after 1.9.0 should use apps/v1
# Kubernetes versions before 1.8.0 should use apps/v1beta1 or extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "openshift-kube-state-metrics.name" . }}
  labels:
{{ include "openshift-kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "openshift-kube-state-metrics.labels.chart" . | indent 4 }}
spec:
  replicas: {{ .Values.kubeStateMetrics.deployment.replicas }}
  selector:
    matchLabels:
      k8s-app: {{ template "openshift-kube-state-metrics.name" . }}
  template:
    metadata:
      labels:
        k8s-app: {{ template "openshift-kube-state-metrics.name" . }}
    spec:
      serviceAccountName: {{ template "openshift-kube-state-metrics.name" . }}
      containers:
      - name: kube-state-metrics
        image: "{{ .Values.kubeStateMetrics.image.name }}:{{ .Values.kubeStateMetrics.image.tag }}"
        args:
        - --collectors=daemonsets, pods, deployments, limitranges, nodes, replicasets, replicationcontrollers, resourcequotas, services, jobs, statefulsets, persistentvolumeclaims, namespaces, horizontalpodautoscalers        
        ports:
        - name: http-metrics
          containerPort: 8080
        - name: telemetry
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 5
      securityContext: {}
      {{- if .Values.kubeStateMetrics.deployment.nodeSelector }}  
      nodeSelector:
        {{ .Values.kubeStateMetrics.deployment.nodeSelector.key }}: "{{ .Values.kubeStateMetrics.deployment.nodeSelector.value }}"
      {{- end }}     



