apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
{{ include "openshift-kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "openshift-kube-state-metrics.labels.chart" . | indent 4 }}
  name: {{ template "openshift-kube-state-metrics.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - extensions
  resourceNames: ["{{ template "openshift-kube-state-metrics.name" . }}"]
  resources:
  - deployments
  verbs:
  - get
  - update
