apiVersion: v1
kind: Service
metadata:
  annotations:    
    service.alpha.openshift.io/serving-cert-secret-name: kube-state-metrics-tls    
    prometheus.io/scrape: '{{ .Values.kubeStateMetrics.service.scrape }}'
    fabric8.io/ingress.annotations: |-
      ingress.kubernetes.io/force-ssl-redirect: {{ .Values.kubeStateMetrics.service.forceSslRedirect }}
      kubernetes.io/ingress.class: {{ .Values.kubeStateMetrics.service.ingressClass }}
      {{- with .Values.kubeStateMetrics.service.annotations }}
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
      {{- end }}
      {{- end }}
    
  name: {{ template "openshift-kube-state-metrics.name" . }}
  labels:
    expose: "{{ .Values.kubeStateMetrics.service.expose }}"
    k8s-app: {{ template "openshift-kube-state-metrics.name" . }}
{{ include "openshift-kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "openshift-kube-state-metrics.labels.chart" . | indent 4 }}
spec:
  clusterIP: None
  ports:
  - name: https-main
    port: 8443
    targetPort: https-main
  - name: https-self
    port: 9443
    targetPort: https-self
  selector:
    k8s-app: {{ template "openshift-kube-state-metrics.name" . }}