apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openshift-kube-state-metrics.name" . }}
  labels:
{{ include "openshift-kube-state-metrics.labels.stakater" . | indent 4 }}
{{ include "openshift-kube-state-metrics.labels.chart" . | indent 4 }}